{
  imports = [
    ./basePackages.nix
    ./battery_monitor.nix
    ./bind.nix
    ./bluetooth.nix
    ./boot.nix
    ./cachix.nix
    ./chromecast.nix
    ./docker.nix
    ./firewall
    ./fonts.nix
    ./fprintd.nix
    ./networking.nix
    ./nix.nix
    ./nixos.nix
    ./nixpkgs.nix
    ./printing.nix
    ./greetd.nix
    ./sound.nix
    ./ssh.nix
    ./style.nix
  ];
}
